# Projeto-vitalog-3/pubspec.yaml
name: vitalog
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ícones
  cupertino_icons: ^1.0.8

  # Gerenciamento de Estado e Serviços
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.3

  # Scanner
  mobile_scanner: ^7.0.1 

  # --- PACOTES ADICIONADOS PARA CORRIGIR OS ERROS ---
  uuid: ^4.4.0                 # Para gerar IDs únicos para os QR Codes
  qr_flutter: ^4.1.0           # Para exibir os QR Codes na tela
  pdf: ^3.10.8                 # Para criar o documento PDF
  printing: ^5.12.0            # Para abrir a interface de impressão do PDF

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"
  web:
    generate: true
  windows:
    generate: true

